---

- name: Ensure we have the latest version of git
  git : repo={{ git_repo }} dest={{ project_path }} accept_hostkey=yes
  tags : git

- name: Ensure user owns our project
  file: state=directory path={{project_path}} owner=ubuntu